### PR TITLE
Always use plugin parameter

### PR DESCRIPTION
**Pull request by gilbertsoft**
To support the eID dispatcher

### CODE REVIEW

**Comment by aimeos** [comment]
Is the "plugin" parameter something that needs to be namespaced, e.g. ai[plugin]?

**Comment by gilbertsoft** [comment]
Don't think so. All parameters were already implemented, but various parameters were only included under some special circumstances. No parameter is used by the plugin, this are informations for typo3 only to call the right plugin. Here are some example requests:

80.93.42.133 - - [04/Feb/2017:00:45:33 +0100] "GET /produkte/?eID=aimeos&plugin=catalog-count HTTP/1.1" 200 1576 "http://www.zwergenfabrik.ch/produkte/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"

80.93.42.133 - - [04/Feb/2017:00:50:36 +0100] "GET /?ai%5Bs_prodcode%5D%5B0%5D=2510000000002&eID=aimeos&plugin=catalog-stock HTTP/1.1" 200 1285 "http://www.zwergenfabrik.ch/detail/d/281/Body/0/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"

80.93.42.133 - - [04/Feb/2017:01:15:30 +0100] "GET /produkte/?eID=aimeos&plugin=catalog-suggest&ai%5Bf_search%5D=bei HTTP/1.1" 200 549 "http://www.zwergenfabrik.ch/produkte/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"

**Comment by gilbertsoft** [comment]
Or do you ask because the if block with the namespacing?

**Comment by aimeos** [comment]
Yes, that was the reason

**Comment by aimeos** [comment]
Could you please add a unit test that covers the new plugin line so the tests are green?

**Comment by gilbertsoft** [comment]
I'm working on an new solution for issue #21 of aimeos-typo3

**Pull request closed without merging**
