### PR TITLE
Set partial- and layoutRootPaths for fluid

### PR DESCRIPTION
**Pull request by DavidHedden**

### CODE REVIEW

**Comment by aimeos** [comment]
Thank you for your PR!
Unfortunately, the unit tests fail because the configuration manager isn't known. Our suggestion would be either to mock the required configuration manager or check with `class_exists()` if it exists first.

**Comment by aimeos** [comment]
Does not work yet: https://travis-ci.org/aimeos/ai-typo3/builds/590161619

**Comment by DavidHedden** [comment]
Bump because of force-push

**Comment by aimeos** [comment]
Thanks a lot! :-)

**Pull request merged**
